### get all boards
GET http://localhost:4000/boards HTTP/1.1

### get single board
GET http://localhost:4000/boards/fb94ace2-2f2b-402e-acf4-dc55037d6111 HTTP/1.1

### add board
POST http://localhost:4000/boards HTTP/1.1
Content-Type: application/json

{
  "title": "Board 3",
  "columns": []
}

### delete board
DELETE http://localhost:4000/boards/fb94ace2-2f2b-402e-acf4-dc55037d6111 HTTP/1.1

### update board
PUT http://localhost:4000/boards/055b7383-7c80-45f2-b132-006781d129e4 HTTP/1.1
Content-Type: application/json

{
    "title": "Board 5",
    "columns": []
}
